/*    */ package com.aionemu.gameserver.ai2.event;
/*    */ 
/*    */ public enum AIEventType
/*    */ {
/* 18 */   ACTIVATE, DEACTIVATE, FREEZE, UNFREEZE, ATTACK, ATTACK_COMPLETE, ATTACK_FINISH, CREATURE_NEEDS_SUPPORT, MOVE_VALIDATE, MOVE_ARRIVED, CREATURE_SEE, CREATURE_NOT_SEE, CREATURE_MOVED, CREATURE_AGGRO, SPAWNED, RESPAWNED, DESPAWNED, DIED, TARGET_REACHED, TARGET_TOOFAR, TARGET_GIVEUP, TARGET_CHANGED, FOLLOW_ME, STOP_FOLLOW_ME, NOT_AT_HOME, BACK_HOME, DIALOG_START, DIALOG_FINISH, DROP_REGISTERED;
/*    */ }